### ISSUE TITLE
Error when importing kadmin

### ISSUE THREAD

**Issue by TheEbolaDoc** [rjancewicz/python-kadmin#65]
# Error :exclamation: 
When importing `kadmin` I get the following error:
```
(env) chris@x ~/lifecycle (master) » python3 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import kadmin
SystemError: bad call flags
```

# System Information :computer: 
`python -V`: `Python 3.8.2`

`uname -a`:
`Linux x 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux`

Let me know if there is more information needed, any help is highly appreciated. :blush:

**Comment by ab8oj** [comment]
I am receiving the same error under Python 3.8.2.  Simplest example:
```
$ python3
Python 3.8.2 (default, Apr  3 2020, 16:33:50) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kadmin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: bad call flags
>>> 
```
```
$ uname -a
Linux mcdev-uam-m1.dsc.umich.edu 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by limburgher** [comment]
I'm seeing this too on Fedora 32, with python 3.8.2.

**Comment by limburgher** [comment]
PR #66 fixes this issue.
