### ISSUE TITLE
Cannot build with pip 20.1

### ISSUE THREAD

**Issue by hocicito1** [rjancewicz/python-kadmin#67]
In pip 20.1, I am unable to install python-kadmin. Here is my output:

```
(venv) [ec2-user@<redacted> ~]$ pip install python-kadmin
Collecting python-kadmin
  Downloading python-kadmin-0.1.2.tar.gz (56 kB)
     |████████████████████████████████| 56 kB 2.1 MB/s
ERROR: More than one .egg-info directory found in /tmp/pip-pip-egg-info-l_xig4fv
```

It is referenced in this issue on pip that installing two packages from a single setup.py file is not supported, which I would guess is the cause here seeing as there are two 'setup' objects defined in this project's setup.py: 

https://github.com/pypa/pip/issues/8201

My environment:
RHEL 8, Python 3.7.7, Pip 20.1

**Comment by hocicito1** [comment]
Here is verbose output:

```
(venv) [ec2-user@<redacted> ~]$ pip install -v python-kadmin
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-_6ib33_u
Created temporary directory: /tmp/pip-req-tracker-pfyf2bea
Initialized build tracking at /tmp/pip-req-tracker-pfyf2bea
Created build tracker: /tmp/pip-req-tracker-pfyf2bea
Entered build tracker: /tmp/pip-req-tracker-pfyf2bea
Created temporary directory: /tmp/pip-install-na9zzoqy
1 location(s) to search for versions of python-kadmin:
* https://pypi.org/simple/python-kadmin/
Fetching project page and analyzing links: https://pypi.org/simple/python-kadmin/
Getting page https://pypi.org/simple/python-kadmin/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/python-kadmin/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/python-kadmin/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/75/50/d1930df2bee139856003635487b13fd5c6ca2969cb06032ab91b71482d63/python-kadmin-0.1.tar.gz#sha256=a75ceb30ad6164431087e42b0023b8d738f3d6f7c3d18dcfd368be047337ba72 (from https://pypi.org/simple/python-kadmin/), version: 0.1
  Found link https://files.pythonhosted.org/packages/d0/64/65447d02c5242ccde0d97a711ccd6eea6c487df577ccd758fdb1a6c77b44/python-kadmin-0.1.1.tar.gz#sha256=3da1a4a8fafe7e1687be7ddea20b802551edf90fa405d4e5590e3c4e93188212 (from https://pypi.org/simple/python-kadmin/), version: 0.1.1
  Found link https://files.pythonhosted.org/packages/8e/80/db00a44f980036388e62d70fe290c44dfa102687a5b16ed8a96e2124cf41/python-kadmin-0.1.2.tar.gz#sha256=eefed8b41c555176356e32a9dec31c65b4bcd05567784a511e5451223fb56c44 (from https://pypi.org/simple/python-kadmin/), version: 0.1.2
Given no hashes to check 3 links for project 'python-kadmin': discarding no candidates
Using version 0.1.2 (newest of versions: 0.1, 0.1.1, 0.1.2)
Collecting python-kadmin
  Created temporary directory: /tmp/pip-unpack-1tpl24mj
  Looking up "https://files.pythonhosted.org/packages/8e/80/db00a44f980036388e62d70fe290c44dfa102687a5b16ed8a96e2124cf41/python-kadmin-0.1.2.tar.gz" in the cache
  Current age based on date: 851
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 851
  Using cached python-kadmin-0.1.2.tar.gz (56 kB)
  Added python-kadmin from https://files.pythonhosted.org/packages/8e/80/db00a44f980036388e62d70fe290c44dfa102687a5b16ed8a96e2124cf41/python-kadmin-0.1.2.tar.gz#sha256=eefed8b41c555176356e32a9dec31c65b4bcd05567784a511e5451223fb56c44 to build tracker '/tmp/pip-req-tracker-pfyf2bea'
    Running setup.py (path:/tmp/pip-install-na9zzoqy/python-kadmin/setup.py) egg_info for package python-kadmin
    Created temporary directory: /tmp/pip-pip-egg-info-dxxsa0lf
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin.egg-info
    writing /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin.egg-info/SOURCES.txt'
    running egg_info
    creating /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin_local.egg-info
    writing /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin_local.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin_local.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin_local.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin_local.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin_local.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-dxxsa0lf/python_kadmin_local.egg-info/SOURCES.txt'
ERROR: More than one .egg-info directory found in /tmp/pip-pip-egg-info-dxxsa0lf
Exception information:
Traceback (most recent call last):
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 333, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 431, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 85, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 550, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 77, in generate_metadata
    return _find_egg_info(egg_info_dir)
  File "/home/ec2-user/venv/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 35, in _find_egg_info
    directory
pip._internal.exceptions.InstallationError: More than one .egg-info directory found in /tmp/pip-pip-egg-info-dxxsa0lf
Removed python-kadmin from https://files.pythonhosted.org/packages/8e/80/db00a44f980036388e62d70fe290c44dfa102687a5b16ed8a96e2124cf41/python-kadmin-0.1.2.tar.gz#sha256=eefed8b41c555176356e32a9dec31c65b4bcd05567784a511e5451223fb56c44 from build tracker '/tmp/pip-req-tracker-pfyf2bea'
Removed build tracker: '/tmp/pip-req-tracker-pfyf2bea'
```

**Comment by vkosuri** [comment]
Hi, I am also facing the same issue with Python2.7, Is there any workaround proposed for this issue?
```
(venv) test@virtual-machine:~$ pip --version
pip 20.1.1 from /home/test/venv/lib/python2.7/site-packages/pip (python 2.7)
(venv) test@virtual-machine:~$
```

**Comment by tucked** [comment]
I think #59 fixes this.
